import type { FilterField, FilterCategory } from "../../../components/FilterModal";

export const filterCategories: FilterCategory[] = [
  { id: "dimensions", label: "Dimensions", icon: "📏" },
  { id: "production", label: "Production", icon: "⚙️" },
  { id: "additional", label: "Additional", icon: "⭐" },
  { id: "financial", label: "Financial", icon: "💰" },
  { id: "dates", label: "Dates", icon: "📅" },
];

export const filterFields: FilterField[] = [
  {
    key: "cut",
    label: "Cut (mm)",
    type: "numberRange",
    category: "dimensions",
    min: 0,
    max: 1000,
    step: 0.1,
    unit: "mm",
  },
  {
    key: "thickness",
    label: "Thickness (mm)",
    type: "numberRange",
    category: "dimensions",
    min: 0,
    max: 500,
    step: 0.1,
    unit: "mm",
  },
  {
    key: "passLevel",
    label: "Pass Level",
    type: "select",
    options: [
      { value: "1", label: "1" },
      { value: "2", label: "2" },
      { value: "3", label: "3" },
      { value: "4", label: "4" },
      { value: "5", label: "5" },
      { value: "6", label: "6" },
    ],
    category: "production",
  },
  {
    key: "setting",
    label: "Setting",
    type: "text",
    placeholder: "Enter setting",
    category: "production",
  },
  {
    key: "qty",
    label: "Quantity",
    type: "numberRange",
    category: "production",
    min: 0,
    max: 10000,
    step: 1,
  },
  {
    key: "priority",
    label: "Priority",
    type: "select",
    options: [
      { value: "Low", label: "Low" },
      { value: "Medium", label: "Medium" },
      { value: "High", label: "High" },
    ],
    category: "additional",
  },
  {
    key: "pipFinish",
    label: "PIP Finish",
    type: "boolean",
    category: "additional",
  },
  {
    key: "sedm",
    label: "SEDM",
    type: "select",
    options: [
      { value: "Yes", label: "Yes" },
      { value: "No", label: "No" },
    ],
    category: "additional",
  },
  {
    key: "rate",
    label: "Rate (₹)",
    type: "numberRange",
    category: "financial",
    min: 0,
    max: 100000,
    step: 0.01,
    unit: "₹",
  },
  {
    key: "totalHrs",
    label: "Total Hours",
    type: "numberRange",
    category: "financial",
    min: 0,
    max: 1000,
    step: 0.001,
    unit: "hrs",
  },
  {
    key: "totalAmount",
    label: "Total Amount (₹)",
    type: "numberRange",
    category: "financial",
    min: 0,
    max: 1000000,
    step: 0.01,
    unit: "₹",
  },
  {
    key: "createdAt",
    label: "Created Date",
    type: "dateRange",
    category: "dates",
  },
];
