import { z } from "zod";

const booleanLike = z.union([z.boolean(), z.string(), z.number()]).optional();
const stringLike = z.union([z.string(), z.number()]).optional();

const createJobInputSchema = z.object({
  id: z.any().optional(),
  _id: z.any().optional(),
  groupId: z.union([z.string(), z.number(), z.bigint()]),
  customer: z.string().optional(),
  rate: stringLike,
  cut: stringLike,
  thickness: stringLike,
  passLevel: stringLike,
  setting: stringLike,
  qty: stringLike,
  sedm: z.string().optional(),
  sedmSelectionType: z.string().optional(),
  sedmRangeKey: z.string().optional(),
  sedmStandardValue: z.string().optional(),
  sedmLengthType: z.string().optional(),
  sedmOver20Length: stringLike,
  sedmLengthValue: stringLike,
  sedmHoles: stringLike,
  sedmEntriesJson: z.string().optional(),
  operationRowsJson: z.string().optional(),
  material: z.string().optional(),
  priority: z.string().optional(),
  description: z.string().optional(),
  remark: z.string().optional(),
  programRefFile: z.string().optional(),
  cutImage: z.any().optional(),
  critical: booleanLike,
  pipFinish: booleanLike,
  totalHrs: stringLike,
  totalAmount: stringLike,
  createdAt: z.string().optional(),
  createdBy: z.string().optional(),
  assignedTo: z.string().optional(),
  refNumber: z.string().optional(),
  startTime: z.string().optional(),
  endTime: z.string().optional(),
  machineHrs: z.string().optional(),
  machineNumber: z.string().optional(),
  opsName: z.string().optional(),
  idleTime: z.string().optional(),
  idleTimeDuration: z.string().optional(),
  lastImage: z.any().optional(),
  qcDecision: z.string().optional(),
  qcReportClosed: booleanLike,
  updatedBy: z.string().optional(),
  updatedAt: z.string().optional(),
});

export const createJobsSchema = z.union([createJobInputSchema, z.array(createJobInputSchema).min(1)]);

export const jobsQuerySchema = z.object({
  limit: z.coerce.number().int().positive().max(100).optional(),
  offset: z.coerce.number().int().min(0).optional(),
  customer: z.string().optional(),
  description: z.string().optional(),
  createdBy: z.string().optional(),
  assignedTo: z.string().optional(),
  passLevel: z.string().optional(),
  setting: z.string().optional(),
  priority: z.string().optional(),
  critical: z.enum(["true", "false"]).optional(),
  pipFinish: z.enum(["true", "false"]).optional(),
  sedm: z.string().optional(),
  createdAt_min: z.string().optional(),
  createdAt_max: z.string().optional(),
  cut_min: z.coerce.number().optional(),
  cut_max: z.coerce.number().optional(),
  thickness_min: z.coerce.number().optional(),
  thickness_max: z.coerce.number().optional(),
  qty_min: z.coerce.number().optional(),
  qty_max: z.coerce.number().optional(),
  rate_min: z.coerce.number().optional(),
  rate_max: z.coerce.number().optional(),
  totalHrs_min: z.coerce.number().optional(),
  totalHrs_max: z.coerce.number().optional(),
  totalAmount_min: z.coerce.number().optional(),
  totalAmount_max: z.coerce.number().optional(),
});
